/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'server-logs': ServerLog;
    media: Media;
    enquiry: Enquiry;
    projects: Project;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'server-logs': ServerLogsSelect<false> | ServerLogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiry: EnquirySelect<false> | EnquirySelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'enquiry-settings': EnquirySetting;
    'interior-page': InteriorPage;
  };
  globalsSelect: {
    'enquiry-settings': EnquirySettingsSelect<false> | EnquirySettingsSelect<true>;
    'interior-page': InteriorPageSelect<false> | InteriorPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'SUPERADMIN' | 'ADMIN';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "server-logs".
 */
export interface ServerLog {
  id: string;
  level: 'info' | 'warn' | 'error';
  event: string;
  message: string;
  method?: string | null;
  path?: string | null;
  requestId?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  category: 'testimonials' | 'news' | 'media' | 'projects' | 'aboutUs' | 'hero' | 'careers' | 'resumes';
  /**
   * Provide a brief title of the image for accessibility and SEO purposes.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnailAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    smallAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mediumAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    largeAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry".
 */
export interface Enquiry {
  id: string;
  name: string;
  email: string;
  type: 'general_enquiry' | 'interior_consultation' | 'site_visit' | 'brochure_request';
  countryCode: string;
  phone: string;
  date: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  slug?: string | null;
  /**
   * Select the property type
   */
  type: 'Apartment' | 'Villas' | 'Plots' | 'Commercial';
  location: string;
  /**
   * Office address to display on the project details page (e.g. City Real Estate Builders & Developers...)
   */
  officeAddress?: string | null;
  /**
   * Description of the location (e.g. This project is strategically situated...)
   */
  locationDescription?: string | null;
  /**
   * Add nearby landmarks and their distance from the project.
   */
  landmarks?:
    | {
        name: string;
        /**
         * e.g., 2 km or 10 mins
         */
        distance: string;
        id?: string | null;
      }[]
    | null;
  status: 'ongoing' | 'upcoming' | 'completed';
  /**
   * Primary thumbnail image for the project listing card.
   */
  image: string | Media;
  /**
   * Multiple images for the main hero slider at the top of the project details page.
   */
  heroImages?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g., 2.5 Cr
   */
  startingAt?: string | null;
  /**
   * e.g., Immediate, Dec 2026
   */
  possession?: string | null;
  /**
   * Add dynamic details specific to this project.
   */
  details?:
    | {
        /**
         * e.g., Area, Configuration, Units, RERA Number
         */
        key: string;
        /**
         * e.g., 2000 sq ft, 2BHK/3BHK, 50, PRM/KA/RERA/...
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A brief summary of the project to display on listing cards.
   */
  shortDescription?: string | null;
  /**
   * Detailed description of the project.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL to a promotional video (e.g., YouTube, Vimeo).
   */
  videoUrl?: string | null;
  /**
   * Google Maps embed URL.
   */
  mapLocationUrl?: string | null;
  /**
   * Upload the primary project brochure (PDF) for the Download Brochure button.
   */
  brochure?: (string | null) | Media;
  /**
   * Images for the project gallery slider.
   */
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        name: string;
        /**
         * Enter the Lucide icon name (e.g., wifi, car, home). Leave blank to use a custom image.
         */
        lucideIcon?: string | null;
        /**
         * Upload a custom SVG or image if not using a Lucide icon.
         */
        customIcon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Structural and material specifications for the project.
   */
  specifications?:
    | {
        /**
         * e.g., Flooring, Electrical, Kitchen
         */
        title: string;
        /**
         * Add multiple bullet points for this specification.
         */
        excerpt?:
          | {
              point: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  floorPlans?:
    | {
        title?: string | null;
        image: string | Media;
        /**
         * Optional text to display under the floor plan image.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  siteProgress?:
    | {
        date: string;
        description?: string | null;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload multiple certificates, bank approvals, or project documents.
   */
  certificates?:
    | {
        /**
         * e.g., RERA Certificate, SBI Home Loan Approved, Brochure
         */
        title: string;
        /**
         * Optional logo (e.g., Bank logo or RERA logo).
         */
        icon?: (string | null) | Media;
        /**
         * The actual PDF document for the customer to download.
         */
        document?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Add FAQs specific to this project.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  collection: string;
  action: 'create' | 'update' | 'delete' | 'read';
  documentId: string;
  timestamp: string;
  user?: (string | null) | User;
  /**
   * Changes made in this operation
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'server-logs';
        value: string | ServerLog;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'enquiry';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "server-logs_select".
 */
export interface ServerLogsSelect<T extends boolean = true> {
  level?: T;
  event?: T;
  message?: T;
  method?: T;
  path?: T;
  requestId?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  category?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnailAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        smallAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mediumAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        largeAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry_select".
 */
export interface EnquirySelect<T extends boolean = true> {
  name?: T;
  email?: T;
  type?: T;
  countryCode?: T;
  phone?: T;
  date?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  location?: T;
  officeAddress?: T;
  locationDescription?: T;
  landmarks?:
    | T
    | {
        name?: T;
        distance?: T;
        id?: T;
      };
  status?: T;
  image?: T;
  heroImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  startingAt?: T;
  possession?: T;
  details?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  shortDescription?: T;
  description?: T;
  videoUrl?: T;
  mapLocationUrl?: T;
  brochure?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        name?: T;
        lucideIcon?: T;
        customIcon?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        title?: T;
        excerpt?:
          | T
          | {
              point?: T;
              id?: T;
            };
        id?: T;
      };
  floorPlans?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        id?: T;
      };
  siteProgress?:
    | T
    | {
        date?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  certificates?:
    | T
    | {
        title?: T;
        icon?: T;
        document?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  collection?: T;
  action?: T;
  documentId?: T;
  timestamp?: T;
  user?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry-settings".
 */
export interface EnquirySetting {
  id: string;
  email: string;
  countryCode: string;
  phone: string;
  telephoneNumber: string;
  address: {
    line1: string;
    line2?: string | null;
    area: string;
    city: string;
    state: string;
    pincode: string;
    mapLink?: string | null;
  };
  links: {
    platformName: string;
    url: string;
    /**
     * Select an icon name from https://lucide.dev/icons/
     */
    iconName: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interior-page".
 */
export interface InteriorPage {
  id: string;
  heroSlides?:
    | {
        /**
         * Background image for the slide
         */
        image: string | Media;
        /**
         * e.g., PREMIUM COLLECTION
         */
        badge: string;
        /**
         * e.g., Elevate Your Everyday Living Experience
         */
        headline: string;
        /**
         * e.g., Bespoke living room designs that combine comfort...
         */
        subtext: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Text shown below the OUR INTERIOR MASTERPIECES heading
   */
  showcaseDescription: string;
  showcaseProjects?:
    | {
        image: string | Media;
        /**
         * e.g., Living Room, Kitchen
         */
        category: string;
        /**
         * e.g., The Sky Penthouse Living Area
         */
        title: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Text shown below the EXCELLENCE IN EVERY DETAIL heading
   */
  whyChooseDescription: string;
  whyChooseFeatures?:
    | {
        /**
         * Lucide icon name (e.g. Layout, ShieldCheck, Compass, Clock, Package, HeartHandshake)
         */
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        /**
         * e.g., AS
         */
        initials: string;
        /**
         * e.g., ANJALI SHARMA
         */
        name: string;
        /**
         * e.g., SKY HIGH PENTHOUSE
         */
        project: string;
        rating: number;
        quote: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry-settings_select".
 */
export interface EnquirySettingsSelect<T extends boolean = true> {
  email?: T;
  countryCode?: T;
  phone?: T;
  telephoneNumber?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        area?: T;
        city?: T;
        state?: T;
        pincode?: T;
        mapLink?: T;
      };
  links?:
    | T
    | {
        platformName?: T;
        url?: T;
        iconName?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interior-page_select".
 */
export interface InteriorPageSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        image?: T;
        badge?: T;
        headline?: T;
        subtext?: T;
        id?: T;
      };
  showcaseDescription?: T;
  showcaseProjects?:
    | T
    | {
        image?: T;
        category?: T;
        title?: T;
        id?: T;
      };
  whyChooseDescription?: T;
  whyChooseFeatures?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        initials?: T;
        name?: T;
        project?: T;
        rating?: T;
        quote?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}