/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'server-logs': ServerLog;
    media: Media;
    enquiry: Enquiry;
    news: News;
    categories: Category;
    'management-designations': ManagementDesignation;
    'about-us-senior-management': AboutUsSeniorManagement;
    'about-us-former-chairmen': AboutUsFormerChairman;
    'about-us-branches': AboutUsBranch;
    'about-us-bulletins': AboutUsBulletin;
    deposits: Deposit;
    loans: Loan;
    home: Home;
    keywords: Keyword;
    services: Service;
    'service-types': ServiceType;
    faq: Faq;
    grievance: Grievance;
    'cyber-security-tags': CyberSecurityTag;
    'employee-engagement': EmployeeEngagement;
    'employee-engagement-categories': EmployeeEngagementCategory;
    'auction-categories': AuctionCategory;
    auctions: Auction;
    'career-departments': CareerDepartment;
    'career-proficiencies': CareerProficiency;
    careers: Career;
    'career-applications': CareerApplication;
    'sales-notice-metadata-keys': SalesNoticeMetadataKey;
    'sales-notice': SalesNotice;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'server-logs': ServerLogsSelect<false> | ServerLogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiry: EnquirySelect<false> | EnquirySelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'management-designations': ManagementDesignationsSelect<false> | ManagementDesignationsSelect<true>;
    'about-us-senior-management': AboutUsSeniorManagementSelect<false> | AboutUsSeniorManagementSelect<true>;
    'about-us-former-chairmen': AboutUsFormerChairmenSelect<false> | AboutUsFormerChairmenSelect<true>;
    'about-us-branches': AboutUsBranchesSelect<false> | AboutUsBranchesSelect<true>;
    'about-us-bulletins': AboutUsBulletinsSelect<false> | AboutUsBulletinsSelect<true>;
    deposits: DepositsSelect<false> | DepositsSelect<true>;
    loans: LoansSelect<false> | LoansSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    keywords: KeywordsSelect<false> | KeywordsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-types': ServiceTypesSelect<false> | ServiceTypesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    grievance: GrievanceSelect<false> | GrievanceSelect<true>;
    'cyber-security-tags': CyberSecurityTagsSelect<false> | CyberSecurityTagsSelect<true>;
    'employee-engagement': EmployeeEngagementSelect<false> | EmployeeEngagementSelect<true>;
    'employee-engagement-categories': EmployeeEngagementCategoriesSelect<false> | EmployeeEngagementCategoriesSelect<true>;
    'auction-categories': AuctionCategoriesSelect<false> | AuctionCategoriesSelect<true>;
    auctions: AuctionsSelect<false> | AuctionsSelect<true>;
    'career-departments': CareerDepartmentsSelect<false> | CareerDepartmentsSelect<true>;
    'career-proficiencies': CareerProficienciesSelect<false> | CareerProficienciesSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'career-applications': CareerApplicationsSelect<false> | CareerApplicationsSelect<true>;
    'sales-notice-metadata-keys': SalesNoticeMetadataKeysSelect<false> | SalesNoticeMetadataKeysSelect<true>;
    'sales-notice': SalesNoticeSelect<false> | SalesNoticeSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'enquiry-settings': EnquirySetting;
    'vision-and-mission': VisionAndMission;
    history: History;
    'chairman-message': ChairmanMessage;
    'shareholder-corner': ShareholderCorner;
    'nre-corners': NreCorner;
    'atm-services': AtmService;
    'mobile-banking': MobileBanking;
    'positive-pay-system': PositivePaySystem;
    'rtgs-neft': RtgsNeft;
    'service-charges': ServiceCharge;
    'customer-care': CustomerCare;
    'cyber-security-awareness': CyberSecurityAwareness;
  };
  globalsSelect: {
    'enquiry-settings': EnquirySettingsSelect<false> | EnquirySettingsSelect<true>;
    'vision-and-mission': VisionAndMissionSelect<false> | VisionAndMissionSelect<true>;
    history: HistorySelect<false> | HistorySelect<true>;
    'chairman-message': ChairmanMessageSelect<false> | ChairmanMessageSelect<true>;
    'shareholder-corner': ShareholderCornerSelect<false> | ShareholderCornerSelect<true>;
    'nre-corners': NreCornersSelect<false> | NreCornersSelect<true>;
    'atm-services': AtmServicesSelect<false> | AtmServicesSelect<true>;
    'mobile-banking': MobileBankingSelect<false> | MobileBankingSelect<true>;
    'positive-pay-system': PositivePaySystemSelect<false> | PositivePaySystemSelect<true>;
    'rtgs-neft': RtgsNeftSelect<false> | RtgsNeftSelect<true>;
    'service-charges': ServiceChargesSelect<false> | ServiceChargesSelect<true>;
    'customer-care': CustomerCareSelect<false> | CustomerCareSelect<true>;
    'cyber-security-awareness': CyberSecurityAwarenessSelect<false> | CyberSecurityAwarenessSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'SUPERADMIN' | 'ADMIN';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "server-logs".
 */
export interface ServerLog {
  id: string;
  level: 'info' | 'warn' | 'error';
  event: string;
  message: string;
  method?: string | null;
  path?: string | null;
  requestId?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  category:
    | 'testimonials'
    | 'news'
    | 'media'
    | 'aboutUs'
    | 'hero'
    | 'deposits'
    | 'loans'
    | 'bulletins'
    | 'nreCorners'
    | 'otherServices'
    | 'digitalBanking'
    | 'cyberSecurity'
    | 'careers'
    | 'resumes'
    | 'salesNotice'
    | 'employeeEngagement'
    | 'auctions';
  /**
   * Provide a brief title of the image for accessibility and SEO purposes.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnailAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    smallAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mediumAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    largeAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry".
 */
export interface Enquiry {
  id: string;
  name: string;
  email: string;
  type: 'general_enquiry' | 'loan_enquiry' | 'deposite_enquiry' | 'nre_enquiry';
  countryCode: string;
  phone: string;
  date: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  status: 'draft' | 'published';
  /**
   * Maximum 100 characters allowed.
   */
  title: string;
  /**
   * Maximum 180 characters allowed.
   */
  shortDescription: string;
  slug?: string | null;
  createdAt: string;
  /**
   * 16:9 aspect ratio recommended.
   */
  coverImage: string | Media;
  /**
   * Select or create news categories/tags.
   */
  category: (string | Category)[];
  images?:
    | {
        /**
         * 1:1 aspect ratio recommended.
         */
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Summary highlights (Bullet points only). Optional.
   */
  summaryHighlights?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords".
 */
export interface Keyword {
  id: string;
  keyword: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-designations".
 */
export interface ManagementDesignation {
  id: string;
  _order?: string | null;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-senior-management".
 */
export interface AboutUsSeniorManagement {
  id: string;
  _order?: string | null;
  /**
   * 1:1 aspect ratio recommended.
   */
  image: string | Media;
  /**
   * Maximum 20 characters.
   */
  firstName: string;
  /**
   * Maximum 20 characters.
   */
  lastName: string;
  type: 'Management' | 'Leadership' | 'Directors' | 'Board of Directors';
  /**
   * Select or create a designation (For Management type).
   */
  designation?: (string | null) | ManagementDesignation;
  /**
   * Select the board designation (Required for Board of Directors type).
   */
  boardDesignation?: ('Chairman' | 'Vice Chairman') | null;
  /**
   * Optional title (For Board of Directors type).
   */
  title?: string | null;
  /**
   * Enter the branch location (Required for Leadership type).
   */
  location?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-former-chairmen".
 */
export interface AboutUsFormerChairman {
  id: string;
  _order?: string | null;
  /**
   * 1:1 aspect ratio recommended.
   */
  image: string | Media;
  firstName: string;
  lastName: string;
  tenures: {
    fromYear: number;
    isPresent?: boolean | null;
    toYear?: number | null;
    id?: string | null;
  }[];
  tenureSummary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-branches".
 */
export interface AboutUsBranch {
  id: string;
  _order?: string | null;
  name: string;
  locationType: 'branch' | 'atm' | 'branch_with_atm';
  branchType?: ('head_office' | 'main_branch' | 'regional_branch' | 'service_branch' | 'extension_counter') | null;
  ifscCode?: string | null;
  city: string;
  state: string;
  district: string;
  pincode: string;
  contactPhone: string;
  email: string;
  fullAddress: string;
  landmark: string;
  latitude: number;
  longitude: number;
  mapLink: string;
  branchManager?: {
    name: string;
    phone: string;
    email: string;
  };
  branchTimings?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        openTime?: string | null;
        closeTime?: string | null;
        isClosed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  holidayNote?: string | null;
  atmAvailability?: ('24x7' | 'branch_hours' | 'custom') | null;
  isMainBranch?: boolean | null;
  isActive: boolean;
  atmServices?: {
    cashWithdrawalAvailable?: boolean | null;
    cashDepositAvailable?: boolean | null;
    passbookPrinterAvailable?: boolean | null;
    miniStatementAvailable?: boolean | null;
    wheelchairAccessible?: boolean | null;
  };
  servicesOffered?:
    | {
        service: string;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-bulletins".
 */
export interface AboutUsBulletin {
  id: string;
  year: string;
  month:
    | 'January'
    | 'February'
    | 'March'
    | 'April'
    | 'May'
    | 'June'
    | 'July'
    | 'August'
    | 'September'
    | 'October'
    | 'November'
    | 'December';
  /**
   * Maximum 120 characters.
   */
  description: string;
  /**
   * Upload the bulletin PDF file.
   */
  pdf: string | Media;
  displayTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deposits".
 */
export interface Deposit {
  id: string;
  accountTypeName: string;
  /**
   * Short name for the account type (Optional)
   */
  shortName?: string | null;
  isFeatured?: boolean | null;
  showInHomePage?: boolean | null;
  slug: string;
  /**
   * Maximum 40 characters.
   */
  shortDescription: string;
  title: string;
  description: string;
  cards?:
    | {
        /**
         * Maximum 30 characters.
         */
        title: string;
        /**
         * Maximum 200 characters.
         */
        description: string;
        /**
         * Interest rate (Used for the second card).
         */
        rate?: string | null;
        tags: {
          /**
           * Maximum 40 characters.
           */
          tag: string;
          /**
           * Maximum 35 characters.
           */
          value: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  termsAndDocumentation?:
    | {
        categoryName: string;
        /**
         * Select an icon name from https://lucide.dev/icons/
         */
        iconName: string;
        additionalSections?:
          | {
              /**
               * Maximum 30 characters.
               */
              title: string;
              /**
               * Maximum 300 characters.
               */
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  rateSummarySection?: {
    showRateSummary?: boolean | null;
    effectiveDate?: string | null;
    rates?:
      | {
          /**
           * Maximum 50 characters.
           */
          tenure: string;
          standardRate: number;
          seniorCitizenRate: number;
          isHighYield?: boolean | null;
          id?: string | null;
        }[]
      | null;
    rateNotice?: string | null;
  };
  perkSection?: {
    showPerks?: boolean | null;
    perks?:
      | {
          title: string;
          /**
           * Select an icon name from https://lucide.dev/icons/
           */
          iconName: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    perkNotice?: string | null;
  };
  officialRegisterSection?: {
    showOfficialRegister?: boolean | null;
    /**
     * Maximum 50 characters allowed
     */
    title?: string | null;
    /**
     * Maximum 200 characters allowed
     */
    description?: string | null;
    auditReport?: {
      /**
       * Maximum 20 characters allowed
       */
      title: string;
      /**
       * Maximum 60 characters allowed
       */
      description: string;
      pdf?: (string | null) | Media;
    };
  };
  withdrawalClauseSection?: {
    showWithdrawalClauses?: boolean | null;
    clauses?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    withdrawalNotice?: string | null;
  };
  verificationSection?: {
    showVerificationCenter?: boolean | null;
    verifications?:
      | {
          pdf: string | Media;
          /**
           * Maximum 50 characters allowed
           */
          name: string;
          /**
           * Maximum 200 characters allowed
           */
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  noticeSection?: {
    showNotice?: boolean | null;
    /**
     * Maximum 50 characters allowed
     */
    noticeTitle?: string | null;
    /**
     * Maximum 400 characters allowed
     */
    noticeDescription?: string | null;
  };
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loans".
 */
export interface Loan {
  id: string;
  /**
   * Maximum 50 characters allowed
   */
  loanTypeName: string;
  isFeatured?: boolean | null;
  showInHomePage?: boolean | null;
  /**
   * Minimum interest rate (Optional)
   */
  minInterest?: number | null;
  /**
   * Maximum interest rate (Optional)
   */
  maxInterest?: number | null;
  slug: string;
  /**
   * Maximum 50 characters allowed
   */
  shortDescription: string;
  /**
   * Maximum 40 characters allowed
   */
  title: string;
  /**
   * Maximum 200 characters allowed
   */
  description: string;
  details: {
    key:
      | 'maxTenure'
      | 'rateOfInterest'
      | 'cibilScore'
      | 'roiFrom'
      | 'marginFrom'
      | 'maxLTV'
      | 'cicScore'
      | 'purpose'
      | 'eligibility'
      | 'margin'
      | 'repayment'
      | 'loanLimit'
      | 'classification'
      | 'npaTrigger'
      | 'authority';
    value: string;
    /**
     * Select an icon name from https://lucide.dev/icons/
     */
    iconName?: string | null;
    id?: string | null;
  }[];
  overview?:
    | {
        categoryName: string;
        sections?:
          | {
              /**
               * Maximum 25 characters allowed
               */
              sectionTitle: string;
              sectionDescription: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  termsAndConditions?:
    | {
        addCondition: string;
        id?: string | null;
      }[]
    | null;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  /**
   * Maximum 50 characters allowed.
   */
  title: string;
  /**
   * Maximum 200 characters allowed.
   */
  description: string;
  /**
   * 1:1 aspect ratio recommended.
   */
  image: string | Media;
  /**
   * Specify the duration (in seconds) for which this slide should remain visible before transitioning to the next one.
   */
  sliderTime?: number | null;
  ctas: {
    ctaText: string;
    /**
     * example : /loans/vehicle-loan or /deposits/gold-loan
     */
    ctaLink: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  _order?: string | null;
  /**
   * Maximum 25 characters allowed.
   */
  serviceName: string;
  type: string | ServiceType;
  /**
   * Select an icon name from https://lucide.dev/icons/
   */
  iconName: string;
  whatsappCountryCode: string;
  whatsappNumber: string;
  contactCountryCode: string;
  contactNumber: string;
  email: string;
  /**
   * Maximum 300 characters allowed.
   */
  description: string;
  /**
   * Select one or more branches.
   */
  serviceNodeNetwork: (string | AboutUsBranch)[];
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types".
 */
export interface ServiceType {
  id: string;
  _order?: string | null;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: string;
  _order?: string | null;
  title: string;
  subTitle: string;
  /**
   * Maximum 151 characters allowed.
   */
  shortDescription: string;
  pageHeading: string;
  /**
   * Maximum 191 characters allowed.
   */
  description: string;
  faqCategories: {
    category: string;
    questions: {
      question: string;
      answer: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * URL-friendly identifier (e.g., loans-and-advances)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grievance".
 */
export interface Grievance {
  id: string;
  name: string;
  email: string;
  countryCode: string;
  phone: string;
  accountNumber: string;
  branch?: string | null;
  existingCustomer: boolean;
  address: string;
  feedback?: string | null;
  complaint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cyber-security-tags".
 */
export interface CyberSecurityTag {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-engagement".
 */
export interface EmployeeEngagement {
  id: string;
  title: string;
  slug?: string | null;
  /**
   * Maximum 200 characters allowed.
   */
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Maximum 200 characters allowed.
   */
  descriptionText?: string | null;
  /**
   * 16:9 aspect ratio recommended.
   */
  coverImage: string | Media;
  category: string | EmployeeEngagementCategory;
  type: 'Upcoming Programs' | 'Celebration and Events' | 'Training and Workshops';
  /**
   * Optional gallery of images for the event.
   */
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Select existing keywords or create new ones.
   */
  keywords?: (string | Keyword)[] | null;
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-engagement-categories".
 */
export interface EmployeeEngagementCategory {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auction-categories".
 */
export interface AuctionCategory {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auctions".
 */
export interface Auction {
  id: string;
  title: string;
  slug: string;
  registryDetails: {
    branchLocation: string;
    noticeReference: string;
    /**
     * Maximum 300 characters allowed.
     */
    institutionalStatement: string;
  };
  category: string | AuctionCategory;
  date: string;
  /**
   * Upload the auction notice (PDF recommended).
   */
  file: string | Media;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-departments".
 */
export interface CareerDepartment {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-proficiencies".
 */
export interface CareerProficiency {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: string;
  title: string;
  slug: string;
  /**
   * Maximum 300 characters allowed.
   */
  description: string;
  location: string;
  type: 'Full-time' | 'Training';
  experience: string;
  department: string | CareerDepartment;
  proficiencies: (string | CareerProficiency)[];
  deadline: string;
  eligibilityCriteria: {
    title: string;
    id?: string | null;
  }[];
  responsibilities: {
    title: string;
    /**
     * Maximum 200 characters allowed.
     */
    description: string;
    id?: string | null;
  }[];
  roadmap: {
    title: string;
    /**
     * Maximum 150 characters allowed.
     */
    description: string;
    id?: string | null;
  }[];
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications".
 */
export interface CareerApplication {
  id: string;
  fullName: string;
  email: string;
  countryCode: string;
  phone: string;
  profileUrl?: string | null;
  appliedJob: string | Career;
  /**
   * Uploaded resume (PDF or DOCX). Maximum allowed size: 5MB.
   */
  resume: string | Media;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-notice-metadata-keys".
 */
export interface SalesNoticeMetadataKey {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-notice".
 */
export interface SalesNotice {
  id: string;
  title: string;
  slug: string;
  date: string;
  contact: string;
  /**
   * Maximum 300 characters allowed.
   */
  description: string;
  /**
   * Maximum 300 characters allowed.
   */
  institutionalPolicyDescription: string;
  /**
   * Optional details about the property schedule.
   */
  scheduleDescription?: string | null;
  metadata?:
    | {
        key: string | SalesNoticeMetadataKey;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload the sales notice document.
   */
  pdf: string | Media;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  collection: string;
  action: 'create' | 'update' | 'delete' | 'read';
  documentId: string;
  timestamp: string;
  user?: (string | null) | User;
  /**
   * Changes made in this operation
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'server-logs';
        value: string | ServerLog;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'enquiry';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'management-designations';
        value: string | ManagementDesignation;
      } | null)
    | ({
        relationTo: 'about-us-senior-management';
        value: string | AboutUsSeniorManagement;
      } | null)
    | ({
        relationTo: 'about-us-former-chairmen';
        value: string | AboutUsFormerChairman;
      } | null)
    | ({
        relationTo: 'about-us-branches';
        value: string | AboutUsBranch;
      } | null)
    | ({
        relationTo: 'about-us-bulletins';
        value: string | AboutUsBulletin;
      } | null)
    | ({
        relationTo: 'deposits';
        value: string | Deposit;
      } | null)
    | ({
        relationTo: 'loans';
        value: string | Loan;
      } | null)
    | ({
        relationTo: 'home';
        value: string | Home;
      } | null)
    | ({
        relationTo: 'keywords';
        value: string | Keyword;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'service-types';
        value: string | ServiceType;
      } | null)
    | ({
        relationTo: 'faq';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'grievance';
        value: string | Grievance;
      } | null)
    | ({
        relationTo: 'cyber-security-tags';
        value: string | CyberSecurityTag;
      } | null)
    | ({
        relationTo: 'employee-engagement';
        value: string | EmployeeEngagement;
      } | null)
    | ({
        relationTo: 'employee-engagement-categories';
        value: string | EmployeeEngagementCategory;
      } | null)
    | ({
        relationTo: 'auction-categories';
        value: string | AuctionCategory;
      } | null)
    | ({
        relationTo: 'auctions';
        value: string | Auction;
      } | null)
    | ({
        relationTo: 'career-departments';
        value: string | CareerDepartment;
      } | null)
    | ({
        relationTo: 'career-proficiencies';
        value: string | CareerProficiency;
      } | null)
    | ({
        relationTo: 'careers';
        value: string | Career;
      } | null)
    | ({
        relationTo: 'career-applications';
        value: string | CareerApplication;
      } | null)
    | ({
        relationTo: 'sales-notice-metadata-keys';
        value: string | SalesNoticeMetadataKey;
      } | null)
    | ({
        relationTo: 'sales-notice';
        value: string | SalesNotice;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "server-logs_select".
 */
export interface ServerLogsSelect<T extends boolean = true> {
  level?: T;
  event?: T;
  message?: T;
  method?: T;
  path?: T;
  requestId?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  category?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnailAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        smallAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mediumAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        largeAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry_select".
 */
export interface EnquirySelect<T extends boolean = true> {
  name?: T;
  email?: T;
  type?: T;
  countryCode?: T;
  phone?: T;
  date?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  shortDescription?: T;
  slug?: T;
  createdAt?: T;
  coverImage?: T;
  category?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  summaryHighlights?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-designations_select".
 */
export interface ManagementDesignationsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-senior-management_select".
 */
export interface AboutUsSeniorManagementSelect<T extends boolean = true> {
  _order?: T;
  image?: T;
  firstName?: T;
  lastName?: T;
  type?: T;
  designation?: T;
  boardDesignation?: T;
  title?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-former-chairmen_select".
 */
export interface AboutUsFormerChairmenSelect<T extends boolean = true> {
  _order?: T;
  image?: T;
  firstName?: T;
  lastName?: T;
  tenures?:
    | T
    | {
        fromYear?: T;
        isPresent?: T;
        toYear?: T;
        id?: T;
      };
  tenureSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-branches_select".
 */
export interface AboutUsBranchesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  locationType?: T;
  branchType?: T;
  ifscCode?: T;
  city?: T;
  state?: T;
  district?: T;
  pincode?: T;
  contactPhone?: T;
  email?: T;
  fullAddress?: T;
  landmark?: T;
  latitude?: T;
  longitude?: T;
  mapLink?: T;
  branchManager?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  branchTimings?:
    | T
    | {
        day?: T;
        openTime?: T;
        closeTime?: T;
        isClosed?: T;
        id?: T;
      };
  holidayNote?: T;
  atmAvailability?: T;
  isMainBranch?: T;
  isActive?: T;
  atmServices?:
    | T
    | {
        cashWithdrawalAvailable?: T;
        cashDepositAvailable?: T;
        passbookPrinterAvailable?: T;
        miniStatementAvailable?: T;
        wheelchairAccessible?: T;
      };
  servicesOffered?:
    | T
    | {
        service?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-bulletins_select".
 */
export interface AboutUsBulletinsSelect<T extends boolean = true> {
  year?: T;
  month?: T;
  description?: T;
  pdf?: T;
  displayTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deposits_select".
 */
export interface DepositsSelect<T extends boolean = true> {
  accountTypeName?: T;
  shortName?: T;
  isFeatured?: T;
  showInHomePage?: T;
  slug?: T;
  shortDescription?: T;
  title?: T;
  description?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        rate?: T;
        tags?:
          | T
          | {
              tag?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  termsAndDocumentation?:
    | T
    | {
        categoryName?: T;
        iconName?: T;
        additionalSections?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  rateSummarySection?:
    | T
    | {
        showRateSummary?: T;
        effectiveDate?: T;
        rates?:
          | T
          | {
              tenure?: T;
              standardRate?: T;
              seniorCitizenRate?: T;
              isHighYield?: T;
              id?: T;
            };
        rateNotice?: T;
      };
  perkSection?:
    | T
    | {
        showPerks?: T;
        perks?:
          | T
          | {
              title?: T;
              iconName?: T;
              description?: T;
              id?: T;
            };
        perkNotice?: T;
      };
  officialRegisterSection?:
    | T
    | {
        showOfficialRegister?: T;
        title?: T;
        description?: T;
        auditReport?:
          | T
          | {
              title?: T;
              description?: T;
              pdf?: T;
            };
      };
  withdrawalClauseSection?:
    | T
    | {
        showWithdrawalClauses?: T;
        clauses?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        withdrawalNotice?: T;
      };
  verificationSection?:
    | T
    | {
        showVerificationCenter?: T;
        verifications?:
          | T
          | {
              pdf?: T;
              name?: T;
              description?: T;
              id?: T;
            };
      };
  noticeSection?:
    | T
    | {
        showNotice?: T;
        noticeTitle?: T;
        noticeDescription?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loans_select".
 */
export interface LoansSelect<T extends boolean = true> {
  loanTypeName?: T;
  isFeatured?: T;
  showInHomePage?: T;
  minInterest?: T;
  maxInterest?: T;
  slug?: T;
  shortDescription?: T;
  title?: T;
  description?: T;
  details?:
    | T
    | {
        key?: T;
        value?: T;
        iconName?: T;
        id?: T;
      };
  overview?:
    | T
    | {
        categoryName?: T;
        sections?:
          | T
          | {
              sectionTitle?: T;
              sectionDescription?: T;
              id?: T;
            };
        id?: T;
      };
  termsAndConditions?:
    | T
    | {
        addCondition?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  sliderTime?: T;
  ctas?:
    | T
    | {
        ctaText?: T;
        ctaLink?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords_select".
 */
export interface KeywordsSelect<T extends boolean = true> {
  keyword?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  serviceName?: T;
  type?: T;
  iconName?: T;
  whatsappCountryCode?: T;
  whatsappNumber?: T;
  contactCountryCode?: T;
  contactNumber?: T;
  email?: T;
  description?: T;
  serviceNodeNetwork?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types_select".
 */
export interface ServiceTypesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  subTitle?: T;
  shortDescription?: T;
  pageHeading?: T;
  description?: T;
  faqCategories?:
    | T
    | {
        category?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        id?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grievance_select".
 */
export interface GrievanceSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  countryCode?: T;
  phone?: T;
  accountNumber?: T;
  branch?: T;
  existingCustomer?: T;
  address?: T;
  feedback?: T;
  complaint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cyber-security-tags_select".
 */
export interface CyberSecurityTagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-engagement_select".
 */
export interface EmployeeEngagementSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  description?: T;
  descriptionText?: T;
  coverImage?: T;
  category?: T;
  type?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-engagement-categories_select".
 */
export interface EmployeeEngagementCategoriesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auction-categories_select".
 */
export interface AuctionCategoriesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auctions_select".
 */
export interface AuctionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  registryDetails?:
    | T
    | {
        branchLocation?: T;
        noticeReference?: T;
        institutionalStatement?: T;
      };
  category?: T;
  date?: T;
  file?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-departments_select".
 */
export interface CareerDepartmentsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-proficiencies_select".
 */
export interface CareerProficienciesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  location?: T;
  type?: T;
  experience?: T;
  department?: T;
  proficiencies?: T;
  deadline?: T;
  eligibilityCriteria?:
    | T
    | {
        title?: T;
        id?: T;
      };
  responsibilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  roadmap?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications_select".
 */
export interface CareerApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  countryCode?: T;
  phone?: T;
  profileUrl?: T;
  appliedJob?: T;
  resume?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-notice-metadata-keys_select".
 */
export interface SalesNoticeMetadataKeysSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-notice_select".
 */
export interface SalesNoticeSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  contact?: T;
  description?: T;
  institutionalPolicyDescription?: T;
  scheduleDescription?: T;
  metadata?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  pdf?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  collection?: T;
  action?: T;
  documentId?: T;
  timestamp?: T;
  user?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry-settings".
 */
export interface EnquirySetting {
  id: string;
  email: string;
  countryCode: string;
  phone: string;
  telephoneNumber: string;
  address: {
    line1: string;
    line2?: string | null;
    area: string;
    city: string;
    state: string;
    pincode: string;
    mapLink?: string | null;
  };
  links: {
    platformName: string;
    url: string;
    /**
     * Select an icon name from https://lucide.dev/icons/
     */
    iconName: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vision-and-mission".
 */
export interface VisionAndMission {
  id: string;
  /**
   * Maximum 150 characters.
   */
  visionDescription: string;
  /**
   * Maximum 150 characters.
   */
  missionDescription: string;
  /**
   * Add objectives (Title max 20 characters, Description max 70 characters).
   */
  objectives?:
    | {
        /**
         * Maximum 20 characters.
         */
        title: string;
        /**
         * Maximum 70 characters.
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history".
 */
export interface History {
  id: string;
  /**
   * Add exactly 4 history points.
   */
  historyPoints: {
    title: string;
    /**
     * Max 250 characters
     */
    description: string;
    id?: string | null;
  }[];
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chairman-message".
 */
export interface ChairmanMessage {
  id: string;
  /**
   * Maximum 120 characters.
   */
  title: string;
  /**
   * 1:1 aspect ratio recommended.
   */
  chairmanImage?: (string | null) | Media;
  chairmanName: {
    firstName: string;
    lastName: string;
  };
  /**
   * Maximum 60 characters.
   */
  quote1?: string | null;
  /**
   * Maximum 200 characters.
   */
  introMessage?: string | null;
  message: string;
  /**
   * Maximum 110 characters.
   */
  quote2?: string | null;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shareholder-corner".
 */
export interface ShareholderCorner {
  id: string;
  /**
   * Add shareholder responsibilities and policies.
   */
  responsibilitiesAndPolicies?:
    | {
        /**
         * Maximum 100 characters.
         */
        title: string;
        description: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nre-corners".
 */
export interface NreCorner {
  id: string;
  title: string;
  description: string;
  cards: {
    /**
     * Maximum 30 characters.
     */
    title: string;
    /**
     * Maximum 200 characters.
     */
    description: string;
    /**
     * Interest rate (Used for the second card).
     */
    rate?: string | null;
    tags: {
      /**
       * Maximum 40 characters.
       */
      tag: string;
      /**
       * Maximum 35 characters.
       */
      value: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  termsAndDocumentation: {
    categoryName: string;
    /**
     * Select an icon name from https://lucide.dev/icons/
     */
    iconName: string;
    additionalSections?:
      | {
          /**
           * Maximum 30 characters.
           */
          title: string;
          /**
           * Maximum 300 characters.
           */
          description: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  rateSummarySection: {
    showRateSummary?: boolean | null;
    effectiveDate?: string | null;
    rates?:
      | {
          /**
           * Maximum 50 characters.
           */
          tenure: string;
          standardRate: number;
          seniorCitizenRate: number;
          isHighYield?: boolean | null;
          id?: string | null;
        }[]
      | null;
    rateNotice?: string | null;
  };
  applicationFormsSection: {
    showApplicationForms?: boolean | null;
    applicationForms?:
      | {
          name: string;
          pdf: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  schemaInfoSection: {
    showSchemaInfo?: boolean | null;
    schemaInfo?: {
      fileName: string;
      pdf: string | Media;
    };
  };
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "atm-services".
 */
export interface AtmService {
  id: string;
  items: {
    title: string;
    /**
     * Select an icon name from https://lucide.dev/icons/
     */
    iconName: string;
    /**
     * Maximum 200 characters allowed.
     */
    description: string;
    id?: string | null;
  }[];
  /**
   * Upload terms and conditions PDF.
   */
  viewTermsPdf: string | Media;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mobile-banking".
 */
export interface MobileBanking {
  id: string;
  title: string;
  /**
   * Maximum 191 characters allowed.
   */
  description1: string;
  /**
   * Maximum 215 characters allowed.
   */
  description2: string;
  features: {
    title: string;
    iconName: string;
    /**
     * Maximum 130 characters allowed.
     */
    description: string;
    id?: string | null;
  }[];
  /**
   * Recommended screenshot size: 828 x 1792 pixels.
   */
  appScreenshots: {
    image: string | Media;
    id?: string | null;
  }[];
  /**
   * Upload terms and conditions PDF.
   */
  termsAndConditionPdf: string | Media;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "positive-pay-system".
 */
export interface PositivePaySystem {
  id: string;
  title: string;
  /**
   * Maximum 200 characters allowed.
   */
  description1: string;
  /**
   * Maximum 330 characters allowed.
   */
  description2: string;
  manuals: {
    title: string;
    iconName: string;
    /**
     * Maximum 100 characters allowed.
     */
    description: string;
    /**
     * Upload PDF manual.
     */
    file: string | Media;
    id?: string | null;
  }[];
  whyPps: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  /**
   * Maximum 172 characters allowed.
   */
  note: string;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rtgs-neft".
 */
export interface RtgsNeft {
  id: string;
  /**
   * Maximum 400 characters allowed.
   */
  guidelineDescription: string;
  /**
   * Unique Bank Identifier (e.g., IFSC Code or Bank Name)
   */
  uniqueBankIdentifier: string;
  /**
   * Bullet points only allowed.
   */
  bulletPoints?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-charges".
 */
export interface ServiceCharge {
  id: string;
  serviceCharges: {
    sectionTitle: string;
    /**
     * Maximum 300 characters allowed.
     */
    description: string;
    /**
     * Bullet points only allowed.
     */
    bulletPoints?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Upload the service charges document (PDF recommended).
     */
    document: string | Media;
  };
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-care".
 */
export interface CustomerCare {
  id: string;
  title: string;
  /**
   * Maximum 164 characters allowed.
   */
  description: string;
  stages: {
    title: string;
    description: string;
    points: {
      heading: string;
      /**
       * Select an icon name from https://lucide.dev/icons/
       */
      iconName: string;
      description: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cyber-security-awareness".
 */
export interface CyberSecurityAwareness {
  id: string;
  title: string;
  /**
   * Maximum 400 characters allowed.
   */
  description: string;
  /**
   * 9:16 Aspect ratio image
   */
  coverImage: string | Media;
  coverImageTitle: string;
  /**
   * Maximum 201 characters allowed.
   */
  coverImageDescription: string;
  cards?:
    | {
        title: string;
        /**
         * Maximum 20 characters allowed.
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  commonThreads?:
    | {
        /**
         * Recommended resolution: 1536x1024 pixels.
         */
        image: string | Media;
        tag: string | CyberSecurityTag;
        title: string;
        /**
         * Maximum 200 characters allowed.
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  trickTechniques?:
    | {
        title: string;
        message: string;
        precaution: string;
        /**
         * Select an icon name from https://lucide.dev/icons/
         */
        iconName: string;
        id?: string | null;
      }[]
    | null;
  protection?:
    | {
        title: string;
        /**
         * Maximum 141 characters allowed.
         */
        description: string;
        /**
         * Select an icon name from https://lucide.dev/icons/
         */
        iconName: string;
        id?: string | null;
      }[]
    | null;
  defenceSystem: {
    /**
     * Recommended resolution: 1536x1024 pixels.
     */
    coverImage: string | Media;
    points?:
      | {
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  seoTitle: string;
  seoDescription: string;
  /**
   * Select existing keywords or create new ones.
   */
  keywords: (string | Keyword)[];
  /**
   * Social sharing image (Open Graph). 1200 x 630 pixels recommended.
   */
  ogImage: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiry-settings_select".
 */
export interface EnquirySettingsSelect<T extends boolean = true> {
  email?: T;
  countryCode?: T;
  phone?: T;
  telephoneNumber?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        area?: T;
        city?: T;
        state?: T;
        pincode?: T;
        mapLink?: T;
      };
  links?:
    | T
    | {
        platformName?: T;
        url?: T;
        iconName?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vision-and-mission_select".
 */
export interface VisionAndMissionSelect<T extends boolean = true> {
  visionDescription?: T;
  missionDescription?: T;
  objectives?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history_select".
 */
export interface HistorySelect<T extends boolean = true> {
  historyPoints?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chairman-message_select".
 */
export interface ChairmanMessageSelect<T extends boolean = true> {
  title?: T;
  chairmanImage?: T;
  chairmanName?:
    | T
    | {
        firstName?: T;
        lastName?: T;
      };
  quote1?: T;
  introMessage?: T;
  message?: T;
  quote2?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shareholder-corner_select".
 */
export interface ShareholderCornerSelect<T extends boolean = true> {
  responsibilitiesAndPolicies?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nre-corners_select".
 */
export interface NreCornersSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        rate?: T;
        tags?:
          | T
          | {
              tag?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  termsAndDocumentation?:
    | T
    | {
        categoryName?: T;
        iconName?: T;
        additionalSections?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  rateSummarySection?:
    | T
    | {
        showRateSummary?: T;
        effectiveDate?: T;
        rates?:
          | T
          | {
              tenure?: T;
              standardRate?: T;
              seniorCitizenRate?: T;
              isHighYield?: T;
              id?: T;
            };
        rateNotice?: T;
      };
  applicationFormsSection?:
    | T
    | {
        showApplicationForms?: T;
        applicationForms?:
          | T
          | {
              name?: T;
              pdf?: T;
              id?: T;
            };
      };
  schemaInfoSection?:
    | T
    | {
        showSchemaInfo?: T;
        schemaInfo?:
          | T
          | {
              fileName?: T;
              pdf?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "atm-services_select".
 */
export interface AtmServicesSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        iconName?: T;
        description?: T;
        id?: T;
      };
  viewTermsPdf?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mobile-banking_select".
 */
export interface MobileBankingSelect<T extends boolean = true> {
  title?: T;
  description1?: T;
  description2?: T;
  features?:
    | T
    | {
        title?: T;
        iconName?: T;
        description?: T;
        id?: T;
      };
  appScreenshots?:
    | T
    | {
        image?: T;
        id?: T;
      };
  termsAndConditionPdf?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "positive-pay-system_select".
 */
export interface PositivePaySystemSelect<T extends boolean = true> {
  title?: T;
  description1?: T;
  description2?: T;
  manuals?:
    | T
    | {
        title?: T;
        iconName?: T;
        description?: T;
        file?: T;
        id?: T;
      };
  whyPps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  note?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rtgs-neft_select".
 */
export interface RtgsNeftSelect<T extends boolean = true> {
  guidelineDescription?: T;
  uniqueBankIdentifier?: T;
  bulletPoints?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-charges_select".
 */
export interface ServiceChargesSelect<T extends boolean = true> {
  serviceCharges?:
    | T
    | {
        sectionTitle?: T;
        description?: T;
        bulletPoints?: T;
        document?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-care_select".
 */
export interface CustomerCareSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  stages?:
    | T
    | {
        title?: T;
        description?: T;
        points?:
          | T
          | {
              heading?: T;
              iconName?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cyber-security-awareness_select".
 */
export interface CyberSecurityAwarenessSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  coverImage?: T;
  coverImageTitle?: T;
  coverImageDescription?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  commonThreads?:
    | T
    | {
        image?: T;
        tag?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  trickTechniques?:
    | T
    | {
        title?: T;
        message?: T;
        precaution?: T;
        iconName?: T;
        id?: T;
      };
  protection?:
    | T
    | {
        title?: T;
        description?: T;
        iconName?: T;
        id?: T;
      };
  defenceSystem?:
    | T
    | {
        coverImage?: T;
        points?:
          | T
          | {
              title?: T;
              id?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}